# OpenSearch Protobuf Schemas
# This module provides convenient access to all protobuf message types
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated modules
from .common_pb2 import *
