"""Synthesized acquisition adapter: JSON state in, JSON fragment out.

Generated by blackhole_agent.capability_acquisition for spec slug 'python-slugify-smart-truncate'.
Do not hand-edit: the vendored tree digest seals this file.
"""

import importlib
import json
import sys
from pathlib import Path

CONFIG = {
  "callable_name": "smart_truncate",
  "entry": "",
  "extra_paths": [
    ".forage-deps/text-unidecode/text-unidecode-1.3/src"
  ],
  "import_name": "slugify",
  "path_root": "python-slugify-8.0.4",
  "provides": "smart_truncate_output",
  "requires": [
    "string"
  ],
  "slug": "python-slugify-smart-truncate"
}

_ROOT = Path(__file__).resolve().parent
for _extra in CONFIG.get("extra_paths") or []:
    sys.path.insert(0, str(_ROOT / _extra))
sys.path.insert(0, str(_ROOT / CONFIG["path_root"]))


def main() -> int:
    state = json.load(sys.stdin)
    module = importlib.import_module(CONFIG["import_name"])
    target = module
    for part in CONFIG["callable_name"].split("."):
        target = getattr(target, part)
    args = [state[key] for key in CONFIG["requires"]]
    result = target(*args)
    json.dump({CONFIG["provides"]: result}, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
