"""Synthesized acquisition adapter: JSON state in, JSON fragment out.

Generated by blackhole_agent.capability_acquisition for spec slug 'oauthlib'.
Do not hand-edit: the vendored tree digest seals this file.
"""

import importlib
import inspect
import json
import sys
from pathlib import Path

CONFIG = {
  "callable_name": "openid.connect.core.grant_types.authorization_code.AuthorizationCodeGrant.id_token_hash",
  "entry": "",
  "import_name": "oauthlib",
  "path_root": "oauthlib-3.3.1",
  "provides": "openid_connect_core_grant_types_authorization_code_authorization",
  "requires": [
    "value"
  ],
  "slug": "oauthlib"
}

_ROOT = Path(__file__).resolve().parent
for _extra in CONFIG.get("extra_paths") or []:
    sys.path.insert(0, str(_ROOT / _extra))
sys.path.insert(0, str(_ROOT / CONFIG["path_root"]))


def _construct_instance(ctor):
    if not inspect.isclass(ctor):
        return None
    for args in ((), ({},), ("",)):
        try:
            return ctor(*args)
        except Exception:
            continue
    return None


def main() -> int:
    state = json.load(sys.stdin)
    module = importlib.import_module(CONFIG["import_name"])
    parts = str(CONFIG["callable_name"]).split(".")
    args = [state[key] for key in CONFIG["requires"]]
    if len(parts) == 1:
        result = getattr(module, parts[0])(*args)
    else:
        parent = module
        imported = str(CONFIG["import_name"])
        for part in parts[:-1]:
            nxt = getattr(parent, part, None)
            if inspect.ismodule(nxt):
                imported = getattr(nxt, "__name__", imported + "." + part) or imported
            elif nxt is None:
                imported = imported + "." + part
                try:
                    nxt = importlib.import_module(imported)
                except Exception:
                    nxt = None
            if nxt is None:
                raise AttributeError(
                    "acquisition callable parent not found: " + ".".join(parts[:-1])
                )
            parent = nxt
        leaf = parts[-1]
        if inspect.isclass(parent):
            raw = inspect.getattr_static(parent, leaf, None)
            if isinstance(raw, (staticmethod, classmethod)):
                result = getattr(parent, leaf)(*args)
            else:
                instance = _construct_instance(parent)
                if instance is None:
                    raise TypeError("cannot construct " + ".".join(parts[:-1]))
                result = getattr(instance, leaf)(*args)
        else:
            result = getattr(parent, leaf)(*args)
    json.dump({CONFIG["provides"]: result}, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
