// Synthesized acquisition adapter: JSON state in, JSON fragment out.
//
// Generated by blackhole_agent.capability_acquisition for spec slug 'forage-js'.
// Do not hand-edit: the vendored tree digest seals this file.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONFIG = {
  "callable_name": "shout",
  "entry": "index.mjs",
  "import_name": "",
  "path_root": ".",
  "provides": "shout_output",
  "requires": [
    "arg0"
  ],
  "slug": "forage-js"
};

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const moduleUrl = pathToFileURL(path.join(ROOT, CONFIG.entry));
const mod = await import(moduleUrl);
let target = mod;
for (const part of CONFIG.callable_name.split(".")) {
  target = target?.[part];
}
if (typeof target !== "function") {
  console.error(`acquisition callable not found: ${CONFIG.callable_name}`);
  process.exit(1);
}
const state = JSON.parse(fs.readFileSync(0, "utf8"));
const args = CONFIG.requires.map((key) => state[key]);
const result = await target(...args);
process.stdout.write(JSON.stringify({ [CONFIG.provides]: result }));
