"""Synthesized acquisition adapter: JSON state in, JSON fragment out.

Generated by blackhole_agent.capability_acquisition for spec slug 'tomli-parser'.
Do not hand-edit: the vendored tree digest seals this file.
"""

import importlib
import json
import sys
from pathlib import Path

CONFIG = {
  "callable_name": "loads",
  "entry": "",
  "import_name": "tomli",
  "path_root": "tomli-2.4.1/src",
  "provides": "parsed_toml",
  "requires": [
    "toml_source"
  ],
  "slug": "tomli-parser"
}

_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(_ROOT / CONFIG["path_root"]))


def main() -> int:
    state = json.load(sys.stdin)
    module = importlib.import_module(CONFIG["import_name"])
    target = module
    for part in CONFIG["callable_name"].split("."):
        target = getattr(target, part)
    args = [state[key] for key in CONFIG["requires"]]
    result = target(*args)
    json.dump({CONFIG["provides"]: result}, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
