// Synthesized acquisition adapter: JSON state in, JSON fragment out.
//
// Generated by blackhole_agent.capability_acquisition for spec slug 'query-string-parse-url'.
// Do not hand-edit: the vendored tree digest seals this file.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONFIG = {
  "callable_name": "parseUrl",
  "entry": "package/index.js",
  "extra_paths": [
    ".forage-deps/decode-uri-component",
    ".forage-deps/filter-obj",
    ".forage-deps/split-on-first"
  ],
  "import_name": "",
  "path_root": ".",
  "provides": "parse_url_output",
  "requires": [
    "arg0",
    "arg1"
  ],
  "slug": "query-string-parse-url"
};

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const extras = CONFIG.extra_paths || [];
const nmDir = path.join(ROOT, "node_modules");
const created = [];
const nmExisted = fs.existsSync(nmDir);
function destFor(extra) {
  const parts = String(extra).split(/[\\/]/).filter(Boolean);
  const idx = parts.indexOf(".forage-deps");
  const rest = idx >= 0 ? parts.slice(idx + 1) : parts.slice(-1);
  return path.join(nmDir, ...rest);
}
try {
  for (const extra of extras) {
    const src = path.join(ROOT, extra);
    const dest = destFor(extra);
    if (!fs.existsSync(src) || fs.existsSync(dest)) {
      continue;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.cpSync(src, dest, { recursive: true });
    created.push(dest);
  }
  const moduleUrl = pathToFileURL(path.join(ROOT, CONFIG.entry));
  const mod = await import(moduleUrl);
  let target = mod;
  for (const part of CONFIG.callable_name.split(".")) {
    target = target?.[part];
  }
  if (typeof target !== "function") {
    const fallback = mod.default;
    if (
      typeof fallback === "function" &&
      (CONFIG.callable_name === "default" || fallback.name === CONFIG.callable_name)
    ) {
      target = fallback;
    } else if (fallback && typeof fallback === "object") {
      const nested = fallback[CONFIG.callable_name];
      if (typeof nested === "function") {
        target = nested;
      }
    }
  }
  if (typeof target !== "function") {
    console.error(`acquisition callable not found: ${CONFIG.callable_name}`);
    process.exitCode = 1;
  } else {
    const state = JSON.parse(fs.readFileSync(0, "utf8"));
    const args = CONFIG.requires.map((key) => state[key]);
    const result = await target(...args);
    process.stdout.write(JSON.stringify({ [CONFIG.provides]: result }));
  }
} finally {
  for (const dest of created.reverse()) {
    try {
      fs.rmSync(dest, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
  if (!nmExisted && fs.existsSync(nmDir)) {
    try {
      fs.rmSync(nmDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
}
