"""Synthesized acquisition adapter: JSON state in, JSON fragment out.

Generated by blackhole_agent.capability_acquisition for spec slug 'marko-htmlrenderer-escape-url'.
Do not hand-edit: the vendored tree digest seals this file.
"""

import importlib
import inspect
import json
import sys
from pathlib import Path

CONFIG = {
  "callable_name": "HTMLRenderer.escape_url",
  "entry": "",
  "import_name": "marko",
  "path_root": "marko-2.2.4",
  "provides": "htmlrenderer_escape_url_output",
  "requires": [
    "raw"
  ],
  "slug": "marko-htmlrenderer-escape-url"
}

_ROOT = Path(__file__).resolve().parent
for _extra in CONFIG.get("extra_paths") or []:
    sys.path.insert(0, str(_ROOT / _extra))
sys.path.insert(0, str(_ROOT / CONFIG["path_root"]))


def _construct_instance(ctor):
    if not inspect.isclass(ctor):
        return None
    for args in ((), ({},), ("",)):
        try:
            return ctor(*args)
        except Exception:
            continue
    return None


def main() -> int:
    state = json.load(sys.stdin)
    module = importlib.import_module(CONFIG["import_name"])
    parts = str(CONFIG["callable_name"]).split(".")
    args = [state[key] for key in CONFIG["requires"]]
    if len(parts) == 1:
        result = getattr(module, parts[0])(*args)
    else:
        parent = module
        for part in parts[:-1]:
            parent = getattr(parent, part)
        leaf = parts[-1]
        if inspect.isclass(parent):
            raw = inspect.getattr_static(parent, leaf, None)
            if isinstance(raw, (staticmethod, classmethod)):
                result = getattr(parent, leaf)(*args)
            else:
                instance = _construct_instance(parent)
                if instance is None:
                    raise TypeError("cannot construct " + ".".join(parts[:-1]))
                result = getattr(instance, leaf)(*args)
        else:
            result = getattr(parent, leaf)(*args)
    json.dump({CONFIG["provides"]: result}, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
