// Synthesized acquisition adapter: JSON state in, JSON fragment out.
//
// Generated by blackhole_agent.capability_acquisition for spec slug 'eta-eta-render-string'.
// Do not hand-edit: the vendored tree digest seals this file.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONFIG = {
  "callable_name": "Eta.renderString",
  "entry": "package/dist/index.mjs",
  "import_name": "",
  "path_root": ".",
  "provides": "eta_render_string_output",
  "requires": [
    "arg0",
    "arg1"
  ],
  "slug": "eta-eta-render-string"
};

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const extras = CONFIG.extra_paths || [];
const nmDir = path.join(ROOT, "node_modules");
const created = [];
const nmExisted = fs.existsSync(nmDir);
function destFor(extra) {
  const parts = String(extra).split(/[\\/]/).filter(Boolean);
  const idx = parts.indexOf(".forage-deps");
  const rest = idx >= 0 ? parts.slice(idx + 1) : parts.slice(-1);
  return path.join(nmDir, ...rest);
}
try {
  for (const extra of extras) {
    const src = path.join(ROOT, extra);
    const dest = destFor(extra);
    if (!fs.existsSync(src) || fs.existsSync(dest)) {
      continue;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.cpSync(src, dest, { recursive: true });
    created.push(dest);
  }
  function resolvePath(root, dotted) {
    let current = root;
    for (const part of String(dotted || "").split(".")) {
      if (current == null) {
        return undefined;
      }
      current = current[part];
    }
    return current;
  }
  function constructInstance(ctor) {
    if (typeof ctor !== "function") {
      return null;
    }
    try {
      return new ctor();
    } catch {
      /* constructor rejected zero arguments */
    }
    try {
      return new ctor({});
    } catch {
      /* constructor rejected empty options */
    }
    try {
      return new ctor("");
    } catch {
      return null;
    }
  }
  function instanceMethod(ctor, leaf) {
    const instance = constructInstance(ctor);
    if (instance && typeof instance[leaf] === "function") {
      return instance[leaf];
    }
    if (ctor && ctor.prototype && typeof ctor.prototype[leaf] === "function") {
      return ctor.prototype[leaf];
    }
    return null;
  }
  const moduleUrl = pathToFileURL(path.join(ROOT, CONFIG.entry));
  const mod = await import(moduleUrl);
  const dotted = String(CONFIG.callable_name).includes(".");
  let target = resolvePath(mod, CONFIG.callable_name);
  if (typeof target !== "function" && dotted) {
    target = resolvePath(mod.default, CONFIG.callable_name);
  }
  let instanceCtor = null;
  if (typeof target !== "function" && dotted) {
    const parts = String(CONFIG.callable_name).split(".");
    const leaf = parts[parts.length - 1];
    const parentName = parts.slice(0, -1).join(".");
    const ctor = resolvePath(mod, parentName) ?? resolvePath(mod.default, parentName);
    const method = instanceMethod(ctor, leaf);
    if (typeof method === "function") {
      target = method;
      instanceCtor = ctor;
    }
  }
  if (typeof target === "function" && dotted) {
    const method = target;
    if (instanceCtor) {
      const leaf = String(CONFIG.callable_name).split(".").pop();
      target = (...args) => {
        const instance = constructInstance(instanceCtor);
        const fn = instance && typeof instance[leaf] === "function" ? instance[leaf] : method;
        return fn.apply(instance, args);
      };
    } else {
      const parentName = String(CONFIG.callable_name).split(".").slice(0, -1).join(".");
      const receiver = resolvePath(mod, parentName) ?? resolvePath(mod.default, parentName);
      target = (...args) => method.apply(receiver, args);
    }
  }
  if (typeof target !== "function") {
    const fallback = mod.default;
    if (
      typeof fallback === "function" &&
      (CONFIG.callable_name === "default" || fallback.name === CONFIG.callable_name)
    ) {
      target = fallback;
    } else if (
      typeof fallback === "function" &&
      Object.prototype.hasOwnProperty.call(fallback, CONFIG.callable_name) &&
      typeof fallback[CONFIG.callable_name] === "function"
    ) {
      const method = fallback[CONFIG.callable_name];
      target = (...args) => method.apply(fallback, args);
    } else if (typeof fallback === "function") {
      const method = instanceMethod(fallback, CONFIG.callable_name);
      if (typeof method === "function") {
        target = (...args) => {
          const instance = constructInstance(fallback);
          const fn =
            instance && typeof instance[CONFIG.callable_name] === "function"
              ? instance[CONFIG.callable_name]
              : method;
          return fn.apply(instance, args);
        };
      }
    }
    if (typeof target !== "function" && fallback && typeof fallback === "object") {
      const nested = fallback[CONFIG.callable_name];
      if (typeof nested === "function") {
        target = nested;
      }
    }
  }
  if (typeof target !== "function") {
    console.error(`acquisition callable not found: ${CONFIG.callable_name}`);
    process.exitCode = 1;
  } else {
    const state = JSON.parse(fs.readFileSync(0, "utf8"));
    const args = CONFIG.requires.map((key) => state[key]);
    const result = await target(...args);
    process.stdout.write(JSON.stringify({ [CONFIG.provides]: result }));
  }
} finally {
  for (const dest of created.reverse()) {
    try {
      fs.rmSync(dest, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
  if (!nmExisted && fs.existsSync(nmDir)) {
    try {
      fs.rmSync(nmDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
}
