# OpenSearch Protobuf Services
# This module provides convenient access to all gRPC service stubs
# without requiring knowledge of the specific _pb2 module names.
#
# This file is automatically generated by tools/generate_init_files.py
# DO NOT EDIT MANUALLY

# Import all classes from the generated service modules
from .document_service_pb2 import *
from .ml_service_pb2 import *
from .search_service_pb2 import *
from .document_service_pb2_grpc import *
from .ml_service_pb2_grpc import *
from .search_service_pb2_grpc import *
