# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opensearch.protobufs.schemas import common_pb2 as protos_dot_schemas_dot_common__pb2


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bulk = channel.unary_unary(
                '/org.opensearch.protobufs.services.DocumentService/Bulk',
                request_serializer=protos_dot_schemas_dot_common__pb2.BulkRequest.SerializeToString,
                response_deserializer=protos_dot_schemas_dot_common__pb2.BulkResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Bulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bulk': grpc.unary_unary_rpc_method_handler(
                    servicer.Bulk,
                    request_deserializer=protos_dot_schemas_dot_common__pb2.BulkRequest.FromString,
                    response_serializer=protos_dot_schemas_dot_common__pb2.BulkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.opensearch.protobufs.services.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.opensearch.protobufs.services.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.opensearch.protobufs.services.DocumentService/Bulk',
            protos_dot_schemas_dot_common__pb2.BulkRequest.SerializeToString,
            protos_dot_schemas_dot_common__pb2.BulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
