# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/services/ml_service.proto
# Protobuf Python Version: 4.25.8
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opensearch.protobufs.schemas import common_pb2 as protos_dot_schemas_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protos/services/ml_service.proto\x12!org.opensearch.protobufs.services\x1a\x1bprotos/schemas/common.proto2\x83\x02\n\tMLService\x12z\n\x12PredictModelStream\x12\x35.org.opensearch.protobufs.MlPredictModelStreamRequest\x1a).org.opensearch.protobufs.PredictResponse\"\x00\x30\x01\x12z\n\x12\x45xecuteAgentStream\x12\x35.org.opensearch.protobufs.MlExecuteAgentStreamRequest\x1a).org.opensearch.protobufs.PredictResponse\"\x00\x30\x01\x42u\n!org.opensearch.protobufs.servicesB\x0eMLServiceProtoP\x01Z>github.com/opensearch-project/opensearch-protobufs/go/servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.services.ml_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!org.opensearch.protobufs.servicesB\016MLServiceProtoP\001Z>github.com/opensearch-project/opensearch-protobufs/go/services'
  _globals['_MLSERVICE']._serialized_start=101
  _globals['_MLSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
