# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opensearch.protobufs.schemas import common_pb2 as protos_dot_schemas_dot_common__pb2


class MLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictModelStream = channel.unary_stream(
                '/org.opensearch.protobufs.services.MLService/PredictModelStream',
                request_serializer=protos_dot_schemas_dot_common__pb2.MlPredictModelStreamRequest.SerializeToString,
                response_deserializer=protos_dot_schemas_dot_common__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.ExecuteAgentStream = channel.unary_stream(
                '/org.opensearch.protobufs.services.MLService/ExecuteAgentStream',
                request_serializer=protos_dot_schemas_dot_common__pb2.MlExecuteAgentStreamRequest.SerializeToString,
                response_deserializer=protos_dot_schemas_dot_common__pb2.PredictResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictModelStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgentStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictModelStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictModelStream,
                    request_deserializer=protos_dot_schemas_dot_common__pb2.MlPredictModelStreamRequest.FromString,
                    response_serializer=protos_dot_schemas_dot_common__pb2.PredictResponse.SerializeToString,
            ),
            'ExecuteAgentStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteAgentStream,
                    request_deserializer=protos_dot_schemas_dot_common__pb2.MlExecuteAgentStreamRequest.FromString,
                    response_serializer=protos_dot_schemas_dot_common__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.opensearch.protobufs.services.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.opensearch.protobufs.services.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictModelStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/org.opensearch.protobufs.services.MLService/PredictModelStream',
            protos_dot_schemas_dot_common__pb2.MlPredictModelStreamRequest.SerializeToString,
            protos_dot_schemas_dot_common__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgentStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/org.opensearch.protobufs.services.MLService/ExecuteAgentStream',
            protos_dot_schemas_dot_common__pb2.MlExecuteAgentStreamRequest.SerializeToString,
            protos_dot_schemas_dot_common__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
