# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/services/search_service.proto
# Protobuf Python Version: 4.25.8
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opensearch.protobufs.schemas import common_pb2 as protos_dot_schemas_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$protos/services/search_service.proto\x12!org.opensearch.protobufs.services\x1a\x1bprotos/schemas/common.proto2\xab\x03\n\rSearchService\x12]\n\x06Search\x12\'.org.opensearch.protobufs.SearchRequest\x1a(.org.opensearch.protobufs.SearchResponse\"\x00\x12\x66\n\tCreatePit\x12*.org.opensearch.protobufs.CreatePitRequest\x1a+.org.opensearch.protobufs.CreatePITResponse\"\x00\x12\x66\n\tDeletePit\x12*.org.opensearch.protobufs.DeletePitRequest\x1a+.org.opensearch.protobufs.DeletePITResponse\"\x00\x12k\n\x12ServerStreamSearch\x12\'.org.opensearch.protobufs.SearchRequest\x1a(.org.opensearch.protobufs.SearchResponse\"\x00\x30\x01\x42y\n!org.opensearch.protobufs.servicesB\x12SearchServiceProtoP\x01Z>github.com/opensearch-project/opensearch-protobufs/go/servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.services.search_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!org.opensearch.protobufs.servicesB\022SearchServiceProtoP\001Z>github.com/opensearch-project/opensearch-protobufs/go/services'
  _globals['_SEARCHSERVICE']._serialized_start=105
  _globals['_SEARCHSERVICE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
