"""Synthesized acquisition adapter: JSON state in, JSON fragment out.

Generated by blackhole_agent.capability_acquisition for spec slug 'apache-airflow-providers-amazon'.
Do not hand-edit: the vendored tree digest seals this file.
"""

import importlib
import importlib.util
import inspect
import json
import os
import sys
import types
from pathlib import Path

CONFIG = {
  "callable_name": "providers.amazon.aws.executors.batch.utils.BatchJobCollection.failure_count_by_id",
  "entry": "",
  "extra_paths": [
    ".forage-deps/apache-airflow-providers-common-compat",
    ".forage-deps/apache-airflow-providers-common-sql",
    ".forage-deps/apache-airflow-providers-http",
    ".forage-deps/boto3",
    ".forage-deps/botocore",
    ".forage-deps/inflection",
    ".forage-deps/watchtower",
    ".forage-deps/jsonpath-ng",
    ".forage-deps/redshift-connector",
    ".forage-deps/asgiref",
    ".forage-deps/pyathena",
    ".forage-deps/jmespath",
    ".forage-deps/sagemaker-studio",
    ".forage-deps/marshmallow",
    ".forage-deps/apache-airflow-core",
    ".forage-deps/apache-airflow-task-sdk",
    ".forage-deps/sqlparse",
    ".forage-deps/more-itertools",
    ".forage-deps/methodtools",
    ".forage-deps/requests",
    ".forage-deps/requests-toolbelt",
    ".forage-deps/aiohttp",
    ".forage-deps/pydantic",
    ".forage-deps/s3transfer",
    ".forage-deps/python-dateutil",
    ".forage-deps/urllib3",
    ".forage-deps/scramp",
    ".forage-deps/pytz",
    ".forage-deps/beautifulsoup4",
    ".forage-deps/lxml",
    ".forage-deps/packaging",
    ".forage-deps/typing-extensions",
    ".forage-deps/fsspec",
    ".forage-deps/tenacity",
    ".forage-deps/psutil",
    ".forage-deps/sqlalchemy",
    ".forage-deps/pandas",
    ".forage-deps/duckdb",
    ".forage-deps/pymysql",
    ".forage-deps/snowflake-sqlalchemy",
    ".forage-deps/sqlalchemy-bigquery",
    ".forage-deps/pydynamodb",
    ".forage-deps/pymongosql",
    ".forage-deps/pymongo-auth-aws",
    ".forage-deps/psycopg2-binary",
    ".forage-deps/pymssql",
    ".forage-deps/awswrangler",
    ".forage-deps/pyiceberg",
    ".forage-deps/numpy",
    ".forage-deps/pyarrow",
    ".forage-deps/aws-embedded-metrics",
    ".forage-deps/deltalake",
    ".forage-deps/sqlglot",
    ".forage-deps/opensearch-py",
    ".forage-deps/vertica-python",
    ".forage-deps/trino",
    ".forage-deps/pyjwt",
    ".forage-deps/oracledb",
    ".forage-deps/backports-datetime-fromisoformat/backports_datetime_fromisoformat-2.0.3",
    ".forage-deps/a2wsgi",
    ".forage-deps/aiosqlite",
    ".forage-deps/alembic",
    ".forage-deps/apache-airflow-providers-common-io",
    ".forage-deps/apache-airflow-providers-smtp",
    ".forage-deps/apache-airflow-providers-standard",
    ".forage-deps/argcomplete",
    ".forage-deps/attrs",
    ".forage-deps/cachetools",
    ".forage-deps/cadwyn",
    ".forage-deps/colorlog",
    ".forage-deps/cron-descriptor",
    ".forage-deps/croniter",
    ".forage-deps/cryptography",
    ".forage-deps/deprecated",
    ".forage-deps/dill",
    ".forage-deps/fastapi",
    ".forage-deps/httpx",
    ".forage-deps/importlib-metadata",
    ".forage-deps/isoduration",
    ".forage-deps/itsdangerous",
    ".forage-deps/jinja2",
    ".forage-deps/jsonschema",
    ".forage-deps/lazy-object-proxy",
    ".forage-deps/libcst",
    ".forage-deps/linkify-it-py",
    ".forage-deps/lockfile",
    ".forage-deps/msgspec",
    ".forage-deps/natsort",
    ".forage-deps/opentelemetry-api",
    ".forage-deps/opentelemetry-exporter-otlp",
    ".forage-deps/opentelemetry-proto",
    ".forage-deps/pathspec",
    ".forage-deps/pendulum",
    ".forage-deps/pluggy",
    ".forage-deps/pygments",
    ".forage-deps/pygtrie",
    ".forage-deps/python-daemon",
    ".forage-deps/python-slugify",
    ".forage-deps/pyyaml",
    ".forage-deps/rich-argparse",
    ".forage-deps/rich",
    ".forage-deps/setproctitle",
    ".forage-deps/starlette",
    ".forage-deps/structlog",
    ".forage-deps/svcs",
    ".forage-deps/tabulate",
    ".forage-deps/termcolor",
    ".forage-deps/universal-pathlib",
    ".forage-deps/uuid6",
    ".forage-deps/uvicorn",
    ".forage-deps/babel",
    ".forage-deps/greenback",
    ".forage-deps/wirerope",
    ".forage-deps/charset-normalizer",
    ".forage-deps/idna",
    ".forage-deps/certifi",
    ".forage-deps/aiohappyeyeballs",
    ".forage-deps/aiosignal",
    ".forage-deps/async-timeout",
    ".forage-deps/frozenlist",
    ".forage-deps/multidict",
    ".forage-deps/propcache",
    ".forage-deps/yarl",
    ".forage-deps/annotated-types",
    ".forage-deps/pydantic-core",
    ".forage-deps/typing-inspection",
    ".forage-deps/six",
    ".forage-deps/asn1crypto",
    ".forage-deps/soupsieve",
    ".forage-deps/greenlet",
    ".forage-deps/tzdata",
    ".forage-deps/snowflake-connector-python",
    ".forage-deps/google-api-core",
    ".forage-deps/google-auth",
    ".forage-deps/google-cloud-bigquery",
    ".forage-deps/pyparsing",
    ".forage-deps/pymongo",
    ".forage-deps/antlr4-python3-runtime",
    ".forage-deps/click",
    ".forage-deps/strictyaml",
    ".forage-deps/zstandard",
    ".forage-deps/arro3-core",
    ".forage-deps/events",
    ".forage-deps/opensearch-protobufs",
    ".forage-deps/lz4",
    ".forage-deps/orjson",
    ".forage-deps/tzlocal",
    ".forage-deps/mako",
    ".forage-deps/tomli",
    ".forage-deps/aiosmtplib",
    ".forage-deps/backports-strenum",
    ".forage-deps/colorama",
    ".forage-deps/cffi",
    ".forage-deps/wrapt",
    ".forage-deps/inspect2",
    ".forage-deps/annotated-doc",
    ".forage-deps/anyio",
    ".forage-deps/httpcore",
    ".forage-deps/zipp",
    ".forage-deps/arrow",
    ".forage-deps/markupsafe",
    ".forage-deps/jsonschema-specifications",
    ".forage-deps/referencing",
    ".forage-deps/rpds-py",
    ".forage-deps/pyyaml-ft",
    ".forage-deps/uc-micro-py",
    ".forage-deps/opentelemetry-exporter-otlp-proto-grpc/opentelemetry",
    ".forage-deps/opentelemetry-exporter-otlp-proto-http/opentelemetry",
    ".forage-deps/protobuf",
    ".forage-deps/text-unidecode",
    ".forage-deps/markdown-it-py",
    ".forage-deps/pathlib-abc",
    ".forage-deps/h11",
    ".forage-deps/sniffio",
    ".forage-deps/outcome",
    ".forage-deps/singledispatch",
    ".forage-deps/pyopenssl",
    ".forage-deps/filelock",
    ".forage-deps/sortedcontainers",
    ".forage-deps/platformdirs",
    ".forage-deps/tomlkit",
    ".forage-deps/googleapis-common-protos",
    ".forage-deps/proto-plus",
    ".forage-deps/pyasn1-modules",
    ".forage-deps/google-cloud-core",
    ".forage-deps/google-resumable-media",
    ".forage-deps/dnspython",
    ".forage-deps/typing",
    ".forage-deps/grpcio"
  ],
  "import_name": "airflow",
  "path_root": "apache_airflow_providers_amazon-9.35.0/src",
  "provides": "providers_amazon_aws_executors_batch_utils_batch_job_collection",
  "requires": [
    "job_id"
  ],
  "slug": "apache-airflow-providers-amazon"
}

if not hasattr(os, "register_at_fork"):
    os.register_at_fork = lambda *args, **kwargs: None

_ROOT = Path(__file__).resolve().parent
for _extra in CONFIG.get("extra_paths") or []:
    sys.path.insert(0, str(_ROOT / _extra))
sys.path.insert(0, str(_ROOT / CONFIG["path_root"]))


def _construct_instance(ctor):
    if not inspect.isclass(ctor):
        return None
    for args in ((), ({},), ("",)):
        try:
            return ctor(*args)
        except Exception:
            continue
    return None


def _load_step(parent, part, imported):
    nxt = getattr(parent, part, None)
    if inspect.ismodule(nxt):
        return nxt, getattr(nxt, "__name__", imported + "." + part) or imported
    if nxt is not None:
        return nxt, imported + "." + part
    imported = imported + "." + part
    try:
        return importlib.import_module(imported), imported
    except Exception:
        pass
    for base in list(getattr(parent, "__path__", []) or []):
        child_dir = str(Path(base) / part)
        child_py = child_dir + ".py"
        if Path(child_dir).is_dir():
            ns = types.ModuleType(imported)
            ns.__path__ = [child_dir]
            sys.modules[imported] = ns
            return ns, imported
        if Path(child_py).is_file():
            spec = importlib.util.spec_from_file_location(imported, child_py)
            if spec is None or spec.loader is None:
                continue
            loaded = importlib.util.module_from_spec(spec)
            sys.modules[imported] = loaded
            spec.loader.exec_module(loaded)
            return loaded, imported
    return None, imported


def main() -> int:
    state = json.load(sys.stdin)
    module = importlib.import_module(CONFIG["import_name"])
    if not hasattr(module, "__version__"):
        module_file = str(getattr(module, "__file__", "") or "")
        for extra in CONFIG.get("extra_paths") or []:
            extra_init = _ROOT.joinpath(str(extra), *str(CONFIG["import_name"]).split("."), "__init__.py")
            try:
                if (not extra_init.is_file()) or str(extra_init.resolve()) == module_file:
                    continue
                extra_text = extra_init.read_text(encoding="utf-8")
            except Exception:
                continue
            marker = "__version__ ="
            if marker in extra_text:
                raw = extra_text.split(marker, 1)[1].splitlines()[0].strip().strip(chr(34) + chr(39))
                if raw:
                    module.__version__ = raw
                    break
    parts = str(CONFIG["callable_name"]).split(".")
    args = [state[key] for key in CONFIG["requires"]]
    if len(parts) == 1:
        result = getattr(module, parts[0])(*args)
    else:
        parent = module
        imported = str(CONFIG["import_name"])
        for part in parts[:-1]:
            nxt, imported = _load_step(parent, part, imported)
            if nxt is None:
                raise AttributeError(
                    "acquisition callable parent not found: " + ".".join(parts[:-1])
                )
            parent = nxt
        leaf = parts[-1]
        if inspect.isclass(parent):
            raw = inspect.getattr_static(parent, leaf, None)
            if isinstance(raw, (staticmethod, classmethod)):
                result = getattr(parent, leaf)(*args)
            else:
                instance = _construct_instance(parent)
                if instance is None:
                    raise TypeError("cannot construct " + ".".join(parts[:-1]))
                result = getattr(instance, leaf)(*args)
        else:
            result = getattr(parent, leaf)(*args)
    json.dump({CONFIG["provides"]: result}, sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
