// Synthesized acquisition adapter: JSON state in, JSON fragment out.
//
// Generated by blackhole_agent.capability_acquisition for spec slug 'ip-address'.
// Do not hand-edit: the vendored tree digest seals this file.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONFIG = {
  "callable_name": "Address4.isValid",
  "entry": "package/dist/ip-address.js",
  "import_name": "",
  "path_root": ".",
  "provides": "address4_is_valid_output",
  "requires": [
    "arg0"
  ],
  "slug": "ip-address"
};

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const extras = CONFIG.extra_paths || [];
const nmDir = path.join(ROOT, "node_modules");
const created = [];
const nmExisted = fs.existsSync(nmDir);
function destFor(extra) {
  const parts = String(extra).split(/[\\/]/).filter(Boolean);
  const idx = parts.indexOf(".forage-deps");
  const rest = idx >= 0 ? parts.slice(idx + 1) : parts.slice(-1);
  return path.join(nmDir, ...rest);
}
try {
  for (const extra of extras) {
    const src = path.join(ROOT, extra);
    const dest = destFor(extra);
    if (!fs.existsSync(src) || fs.existsSync(dest)) {
      continue;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.cpSync(src, dest, { recursive: true });
    created.push(dest);
  }
  function resolvePath(root, dotted) {
    let current = root;
    for (const part of String(dotted || "").split(".")) {
      if (current == null) {
        return undefined;
      }
      current = current[part];
    }
    return current;
  }
  const moduleUrl = pathToFileURL(path.join(ROOT, CONFIG.entry));
  const mod = await import(moduleUrl);
  const dotted = String(CONFIG.callable_name).includes(".");
  let target = resolvePath(mod, CONFIG.callable_name);
  if (typeof target !== "function" && dotted) {
    target = resolvePath(mod.default, CONFIG.callable_name);
  }
  if (typeof target === "function" && dotted) {
    const parentName = String(CONFIG.callable_name).split(".").slice(0, -1).join(".");
    const receiver = resolvePath(mod, parentName) ?? resolvePath(mod.default, parentName);
    const method = target;
    target = (...args) => method.apply(receiver, args);
  }
  if (typeof target !== "function") {
    const fallback = mod.default;
    if (
      typeof fallback === "function" &&
      (CONFIG.callable_name === "default" || fallback.name === CONFIG.callable_name)
    ) {
      target = fallback;
    } else if (
      typeof fallback === "function" &&
      Object.prototype.hasOwnProperty.call(fallback, CONFIG.callable_name) &&
      typeof fallback[CONFIG.callable_name] === "function"
    ) {
      const method = fallback[CONFIG.callable_name];
      target = (...args) => method.apply(fallback, args);
    } else if (
      typeof fallback === "function" &&
      fallback.prototype &&
      typeof fallback.prototype[CONFIG.callable_name] === "function"
    ) {
      const method = fallback.prototype[CONFIG.callable_name];
      target = (...args) => method.apply(new fallback(), args);
    } else if (fallback && typeof fallback === "object") {
      const nested = fallback[CONFIG.callable_name];
      if (typeof nested === "function") {
        target = nested;
      }
    }
  }
  if (typeof target !== "function") {
    console.error(`acquisition callable not found: ${CONFIG.callable_name}`);
    process.exitCode = 1;
  } else {
    const state = JSON.parse(fs.readFileSync(0, "utf8"));
    const args = CONFIG.requires.map((key) => state[key]);
    const result = await target(...args);
    process.stdout.write(JSON.stringify({ [CONFIG.provides]: result }));
  }
} finally {
  for (const dest of created.reverse()) {
    try {
      fs.rmSync(dest, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
  if (!nmExisted && fs.existsSync(nmDir)) {
    try {
      fs.rmSync(nmDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  }
}
